const unsplashed = "https://source.unsplash.com/200x200/"

const photos: string[] = [
  `${unsplashed}?beach`,
  `${unsplashed}?space`,
  `${unsplashed}?office`,
  `${unsplashed}?house`,
  `${unsplashed}?shops`,
  `${unsplashed}?hat`,
  `${unsplashed}?park`,
  `${unsplashed}?food`,
  `${unsplashed}?club`,
  `${unsplashed}?dance`,
  `${unsplashed}?sun`,
  `${unsplashed}?stars`,
  `${unsplashed}?friends`,
  `${unsplashed}?bank`,
  `${unsplashed}?laptop`,
  `${unsplashed}?book`,
  `${unsplashed}?table`,
  `${unsplashed}?mountain`,
  `${unsplashed}?school`,
  `${unsplashed}?watch`,
  `${unsplashed}?bag`,
  `${unsplashed}?family`,
  `${unsplashed}?shops`,
  `${unsplashed}?forrest`,
  `${unsplashed}?city`,
  `${unsplashed}?bus`,
  `${unsplashed}?clock`,
  `${unsplashed}?train`,
  `${unsplashed}?bottle`,
]

export default photos
