export const TRENDING_MOVIES = "trending_movies"
export const WAR_MOVIES = "war_movies"
export const POPULAR_MOVIES = "popular_movies"
export const ACTION_MOVIES = "action_movies"
export const FANTASY_MOVIES = "fantasy_movies"
export const SCIENCE_FICTION_MOVIES = "science_fiction_movies"
export const CARTOONS = "cartoons"
export const GENRES = "genres"
